name: pyart_mybinder
dependencies:
- backports_abc=0.4=py27_0
- cairo=1.12.18=6
- curl=7.43.0=1
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- hdf5=1.8.15.1=2
- ipykernel=4.2.2=py27_0
- ipython=4.0.3=py27_0
- ipython-notebook=4.0.4=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_core=4.0.6=py27_0
- krb5=1.13.2=0
- libgfortran=1.0=0
- libnetcdf=4.3.3.1=1
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.1=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- netcdf4=1.2.1=np110py27_0
- notebook=4.1.0=py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=3
- openssl=1.0.1k=1
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- pixman=0.32.6=0
- ptyprocess=0.5=py27_0
- pyart=1.5.0=nppy27_0
- pycairo=1.10.0=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.16.1=np110py27_0
- setuptools=19.2=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- wheel=0.26.0=py27_1
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - arm-pyart==1.5.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - smop==0.23

